### ISSUE TITLE
[ UPDATE ] - 💻 Readme.md update Needed 🔥

### ISSUE THREAD

**Issue by sachin-duhan26** [sachin-duhan26/COMPETITVE-PROGRAMMING#6]
The current readme file is very simple and does not explain anything about the problems that are being solved under the repo. A simple yet self-explanatory readme file is needed that meet the features listed below.

- How to start CP
- Learning resources
- Youtube links
- Study material for beginners

Feel free to suggest more creative thoughts on this.
```
HAPPY CODING
```

**Comment by MilindGupta-Creator** [comment]
hey can you handle me over this work

**Comment by sachin-duhan26** [comment]
I'm glad to have you here @MilindGupta-Creator ,
Looking forward to it.

**Comment by sachin-duhan26** [comment]
hello @MilindGupta-Creator,
did u get some to work on the issue?

**Comment by 2tanayk** [comment]
hey @sachin-duhan26 may I work on this issue?I would be glad to help,so do let me know😀

**Comment by sachin-duhan26** [comment]
sure @2tanayk

**Comment by 2tanayk** [comment]
will work on this tom,thank you for assignment!
